language: cpp
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libglu1-mesa-dev
      - libxxf86vm-dev 
      - cmake
matrix:
  include:
    - os: linux
      compiler: gcc-4.8
      script:
        - CXXFLAGS=-DNANOVG_GL_NO_UNIFORMBUFFER=1 cmake -DCMAKE_CXX_COMPILER=g++-4.8
        - make -j 2
    - os: osx
      compiler: clang
      script:
        - cmake
        - make -j 2
